name: StaticPage21

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Install Node JS
      uses: action/setup-node@v2-beta
      with:
          node-version: 12
    - name: install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./ staticpage212.surge.sh - —token ${{ secrets.STATIC }}
